### ISSUE TITLE
Exceptions are not catched

### ISSUE THREAD

**Issue by matheusdev** [janhenkgerritsen/codeception-laravel5#12]
If I run a functional test and some error occur (a route not defined, for example) no feedback is given. After digging the code I figure out that L4 exceptions when in testing environment were rethrowed (https://github.com/laravel/framework/blob/4.2/src/Illuminate/Foundation/Application.php#L749) but in L5 are catched by application's exception handler. I tried to make the L5 module act also as a handler and worked but is right this approach?

**Comment by janhenkgerritsen** [comment]
How you handle exceptions in your application is your own decision. If you like to re-throw them in the testing environment you can do that, but I would not do that myself. Your application should handle exceptions gracefully and you should test this. If an exception occurs because you have not yet implemented any code for a specific test, the test fails and you can check the output in the `_output` directory in your tests directory. This directory contains HTML files with the output for failed tests. If you use the default error handling for Laravel 5 these files will contain output for the exceptions in case an exception is thrown which causes your test to fail.

**Comment by matheusdev** [comment]
Yes, I understand your point. I just wanted that exceptions were displayed in console like what happens using Laravel 4. 
![captura de tela 2015-01-26 as 13 49 01](https://cloud.githubusercontent.com/assets/8084685/5902501/25aba212-a562-11e4-82a5-9f37a5704421.png)
Above the test fails at step 2 while Laravel 5 just stops at step 3 giving the idea that everything before was correct.
![captura de tela 2015-01-26 as 13 47 20](https://cloud.githubusercontent.com/assets/8084685/5902480/f281df50-a561-11e4-89b8-f813adfb7690.png)

**Comment by janhenkgerritsen** [comment]
I agree that it is nicer too see the exception in the console. However, the problem is that the default Laravel 5 installation handles all exceptions, so they  cannot be catched by Codeception if you do not change this behavior yourself.

**Comment by matheusdev** [comment]
I tried a quickfix making `Codeception\Module\Laravel5` implement `Illuminate\Contracts\Debug\ExceptionHandler` but that solution duplicates code and give too much responsibility to the module. I will treat testing exceptions myself to solve that issue, thanks for the help!
