### ISSUE TITLE
Module maintenance

### ISSUE THREAD

**Issue by jonathantorres** [janhenkgerritsen/codeception-laravel5#14]
Is this module going to be maintained here? Maybe I submitted this PR https://github.com/Codeception/Codeception/pull/1782 on the wrong place?

**Comment by janhenkgerritsen** [comment]
I was not going to maintain the package here, but I changed my mind and will also maintain the package over here. This way this repository always makes the latest version of the module available for use, even if it is not included in the latest version of Codeception yet. And I can simply create pull requests for Codeception based on the files in this repository to add the latest version to Codeception, because the module consists of only two files.

For now we can keep discussing your PR at your issue at the Codeception repository.
