### ISSUE TITLE
seeSessionHasErrors() not working

### ISSUE THREAD

**Issue by abstractFlo** [janhenkgerritsen/codeception-laravel5#5]
hi, can you tell me why as the seeSessionHasErrors () command in Laravel 5 does not work?

I have your testing provider in my system. But somehow I can not access the session in a functional test.

I hope you can help me here yet: D

**Comment by janhenkgerritsen** [comment]
The [ShareErrorsFromSession](https://github.com/laravel/framework/blob/master/src/Illuminate/View/Middleware/ShareErrorsFromSession.php) middleware reads the `errors` field from the session and adds them to the view. Because the errors are flashed to the next request, they are removed from the session after this middleware reads them. However, the module still checked if the session data contained an errors entry.

So I adapted the Laravel 5 module a bit. I renamed two methods and added another for convenience:

renamed `seeSessionHasErrors()` to `seeFormHasErrors()`
renamed `seeSessionErrorMessage(array $bindings)` to `seeFormErrorMessages(array $bindings)`
added `seeFormErrorMessage($key, $errorMessage)`

These changes are already released with version 1.0.6. I also added another test to the sample app that tests these methods.
